spring.application.name=cams-auth
server.port=${SERVER_PORT:8080}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_SCHEMA_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.mail.host=${SMTP_HOST}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=${SMTP_PORT:587}
spring.mail.properties.mail.smtp.auth=${SMTP_USE_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED:true}
application.security.secret-key=${SECURITY_SECRET_KEY}
application.frontend-origin=${FRONTEND_ORIGIN:http://localhost:3000}
logging.level.web=${LOG_LEVEL:INFO}
spring.mvc.log-request-details=${LOG_REQUEST_DETAILS:false}