name: "Build and Publish OCI Image"

on:
  workflow_call:

jobs:
  build-app-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/common

      - name: Build OCI Image
        run: ./gradlew bootBuildImage --imageName ghcr.io/cams_${{github.repository}}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish OCI Image
        run: docker push ghcr.io/cams_${{github.repository}}:latest