name: "Coverage Check"

on:
  workflow_call:

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/common

      - name: Generate Jacoco Report
        run: ./gradlew --no-daemon jacocoTestReport

      - name: Run Jacoco Coverage Verification
        run: ./gradlew --no-daemon jacocoTestCoverageVerification
