name: CI Pipeline [Main Branch]

on:
  push:
    branches:
      - main

jobs:
  compile-and-test:
    uses: ./.github/workflows/components/compile-and-test.yaml

  coverage-check:
    uses: ./.github/workflows/components/coverage-check.yaml
    needs: compile-and-test

  sonar:
    uses: ./.github/workflows/components/sonar-scan.yaml
    needs: coverage-check

  build-and-publish-image:
    uses: ./.github/workflows/components/build-and-publish-image.yaml
    needs: sonar
