name: CI Pipeline [Non-Trunk or PR]

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile-and-test:
    uses: ./.github/workflows/compile-and-test.yaml

  coverage-check:
    uses: ./.github/workflows/coverage-check.yaml
    needs: compile-and-test

  sonar:
    uses: ./.github/workflows/sonar-scan.yaml
    needs: coverage-check
