name: CI Pipeline [Pull-Request]

on:
  pull_request:

jobs:
  compile-and-test:
    uses: ./.github/workflows/compile-and-test.yaml

  coverage-check:
    uses: ./.github/workflows/coverage-check.yaml
    needs: compile-and-test

  sonar:
    uses: ./.github/workflows/sonar-scan.yaml
    needs: coverage-check
